### ISSUE TITLE
feat: create a watchOS app

### ISSUE THREAD

**Issue by hyun99999** [Secret-Of-SwiftUI/SOS-gyuriracha#29]
_**SwiftUI Tutorial**_

## 📣 Issue
- create a watchOS app

## ☑️ Todo
- [x] add watchOS target
- [x] share files between targets(Landmarks and WatchLandmarks)
- [x] create the detail view 
- [x] add the Landmarks list
- [x] create a Custom Notification Interface
